#ifndef BLE_HANDLER_CONSTANTS_H
#define BLE_HANDLER_CONSTANTS_H

namespace BleSettings {
    const int BLE_DISCONNECT_DELAY_SECONDS = 2;
    const int BLE_DISCONNECT_DELAY = BLE_DISCONNECT_DELAY_SECONDS * 1000;
    const int BLE_RESPONSE_DELAY_SECONDS = 4;
    const int BLE_RESPONSE_DELAY = BLE_RESPONSE_DELAY_SECONDS * 1000; 
}

#endif